name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pdocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - run: python3 -m pip install maturin pdoc

      - run: python3 -m maturn build

      - run: pip install --no-index --find-links target/wheels/ dwat

      - run: python3 -m pdoc -o docs/ python_stubs/dwat

      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/
